// import './day-01/index.ts'
// import './day-02/index.ts'
// import './day-03/index.ts'
// import './day-04/index.ts'
// import './day-05/index.ts'
// import './day-06/index.ts'
// import './day-07/index.ts'
// import './day-08/index.ts'
// import './day-09/index.ts'
// import './day-10/index.ts'
// import './day-11/index.ts'
// import './day-12/index.ts'
// import './day-13/index.ts'
// import './day-14/index.ts'
// import './day-15/index.ts'
import './day-16/index.ts'